### ISSUE TITLE
Require "dev-master", seriously?

### ISSUE THREAD

**Issue by OzanKurt** [yajra/laravel-datatables-buttons#1]
It's pretty easy to create an alpha release...

So that people can work with your package without messing with their `composer.json`.

**Comment by yajra** [comment]
Oh, you can use 7.* on your composer. It has a branch alias on dev-master.. But it's for Laravel 5.4 only since there are a lot of breaking changes. Thanks!

**Comment by yajra** [comment]
Whoops this is the buttons repo.. Still have not updated this one..

**Comment by OzanKurt** [comment]
It would be great if you can create an alpha/beta release for use with laravel 5.4 then. 

:+1:

**Comment by yajra** [comment]
I already added a 1.* branch alias and should be installable now. However, we have some problem using laravelcollective/html package as it does not have support for Laravel 5.4 atm even using their master branch. I am currently using my fork version for temp support.

**Comment by yajra** [comment]
Will release a stable version once https://github.com/LaravelCollective/html/pull/276 is merged or support for Laravel 5.4 is established.

**Comment by yajra** [comment]
v1.0.0 released 🚀 . Thanks!
