### ISSUE TITLE
 print only the columns visible with the selected rows

### ISSUE THREAD

**Issue by raar4ever** [yajra/laravel-datatables-buttons#107]
### Summary of problem or feature request

I want to print only the columns shown with the selected rows

### System details

- Operating System win10
- PHP Version 7.2
- Laravel Version 6.2
- Laravel-DataTables Version 1.5

**Comment by yajra** [comment]
I think this is possible but might need a bit of work. For a start, see https://github.com/yajra/laravel-datatables-buttons/pull/78 and modify the script to include the selected rows id. On the server-side, just add a filter on the ids provided.

**Comment by yajra** [comment]
Still not supported by js library so closing for now.
