### ISSUE TITLE
Upgrading from Laravel 5 to Laravel 6 with service implementation - $this->datatables is null

### ISSUE THREAD

**Issue by phpguru** [yajra/laravel-datatables-buttons#112]
We have been using Yajra DataTables with Laravel 5 for a few years and have built up a library of over 50 of them, basically for the index page of a BREAD UI. It's finally time to upgrade, and  We're using the service implementation, which looks like this. 

The current code is working against     

    "yajra/laravel-datatables-oracle": "^6.0",

Here is the Controller:

    <?php

    namespace App\Http\Controllers;

    use Illuminate\Http\Request;
    use Illuminate\Support\Facades\Validator;
    use App\DataTables\WidgetDataTable;
    use App\Models\Widget;
    use Illuminate\Support\Facades\Auth;
    use App\Models\Widgetaccount;
    use App\Events\Widgetcrud;
    use App\DataTables\WidgetHistoryDataTable;
    use Illuminate\Support\Facades\DB;

    class WidgetController extends Controller
    {
        /**
         * Create a new controller instance
         *
         * @return void
         */
        public function __construct()
        {
            $this->middleware('permission:widget_view', ['only' => ['index', 'history']]);
            $this->middleware('permission:widget_create', ['only' => ['create','store']]);
            $this->middleware('permission:widget_edit', ['only' => ['edit','update']]);
            $this->middleware('permission:widget_delete', ['only' => ['destroy']]);
        }

        /**
         * Display a listing of the resource.
         *
         * @param  object $dataTable
         * @return \Illuminate\Http\Response
         */
        public function index(WidgetDataTable $dataTable)
        {
            return $dataTable->render('widget.index', [
                'title' => 'Manage Widgets',
            ]);
        }

        // other methods here

    }

Here is the DataTables class:

    <?php

    namespace App\DataTables;

    use Illuminate\Support\Facades\DB;
    use Yajra\DataTables\Services\DataTable;
    use Illuminate\Support\Facades\Auth;

    class widgetDataTable extends DataTable
    {

        /**
         * Display ajax rwidgetonse.
         *
         * @return \Illuminate\Http\JsonResponse
         */
        public function ajax()
        {
            return $this->datatables
                ->queryBuilder($this->query())
                ->editColumn(
                    'edit accounts',
                    function ($widget) {
                        return '<a href="' . route('widgetaccounts.index', 'widgetid=' . $widget->id)
                            . '" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-edit"></i> </a>';

                    }
                )
                ->editColumn(
                    'documentation',
                    function ($widget) {
                        if ($widget->documentation != null) {
                            return '<a href="javascript:void(0)" data-value="' . $widget->documentation .
                                '" class="btn btn-xs btn-primary opendocument">View</a>';
                        } else {
                            return '';
                        }
                    }
                )
                ->addColumn(
                    'action',
                    function ($widget) {
                        return '<a href="' . route('widgets.edit', $widget->id) .
                            '" class="btn btn-xs btn-primary" dusk="widget-edit-button-'.$widget->id .'"><i class="glyphicon glyphicon-edit"></i> Edit</a>
                <a href="javascript:void(0)" data-remote="' . route('widgets.destroy', $widget->id) .
                        '" class="btn btn-xs btn-danger btn-delete" dusk="widget-delete-button-'.$widget->id .'"><i class="glyphicon glyphicon-trash"></i>Delete</a>';
                    }
                )
                ->make(true);
        }

        /**
         * Get the query object to be processed by dataTables.
         *
         * @return \Illuminate\Database\Eloquent\Builder|
         */
        public function query()
        {
            $widget_id = null;
            if ($this->request()->has("widgetid")) {
                $widget_id = $this->request()->get("widgetid");
            }

            $query = DB::connection('dashboard')
                ->table('widgets')
                ->join('users', 'users.id', '=', 'widgets.user_id')
                ->whereNull('widgets.deleted_at')
                ->when($widget_id,
                    function ($queryvar, $widget_id) {
                        return $queryvar->where('widgets.id', $widget_id);
                })
                ->select(
                    'widgets.id',
                    'widgets.name',
                    'widgets.active',
                    'users.name as username',
                    'widgets.documentation',
                    'widgets.created_at',
                    'widgets.updated_at',
                    'widgets.deleted_at'
                );

            return $this->applyScopes($query);
        }

        /**
         * Optional method if you want to use html builder.
         *
         * @return \Yajra\Datatables\Html\Builder
         */
        public function html()
        {
            if (Auth::user()->can('distribution_manage_widget_lists_edit')) {
                return $this->builder()
                        ->columns($this->getColumns())
                        ->ajax('')
                        ->addAction(['width' => '80px'])
                        ->parameters([
                            'dom' => 'lBfrtip',
                            'buttons' => ['csv', 'excel'],
                            'pageLength' => 50
                ]);
            }else{
                return $this->builder()
                        ->columns($this->getColumns())
                        ->ajax('')
                        ->parameters([
                            'dom' => 'lBfrtip',
                            'buttons' => ['csv', 'excel'],
                            'pageLength' => 50
                ]);
            }
        }

        /**
         * Get columns.
         *
         * @return array
         */
        protected function getColumns()
        {
            return [
                'id',
                'name',
                'active',
                'documentation' => ['searchable' => false, 'orderable' => false],
                'edit accounts' => ['searchable' => false, 'orderable' => false],
                'last edited by' => ['name' => 'users.name', 'data' => 'username'],
                'created_at',
                'updated_at',
            ];
        }

        /**
         * Get filename for export.
         *
         * @return string
         */
        protected function filename()
        {
            return 'widgetdatatables_'.time();
        }
    }

Here is the view:

    @extends('layouts.main')
    @section('content')
    @include('partials.panel-open', [ 'title' => "Manage widgets" ])
    <form action="{{route('widgetsearch')}}"  method="POST">
            {{ csrf_field() }}
    <div class="search_button_group">
      <div class="row">
        <div class="col-sm-4 col-sm-offset-2">
          <label>Search for widget-related Settings: </label>
        </div>
        <div class="col-sm-6">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="" name="search" aria-describedby="basic-addon1" required="required">
            <button class="input-group-addon btn btn-primary" id="basic-addon1" type="submit">Go</button>
          </div>
        </div>
      </div>
    </div>
    </form>
    <div class="row form-group">
      <div class="col-sm-6">
          @permission(('widget_create'))
          <a href="{{ route('widgets.create') }}" class="btn btn-primary" dusk="widget-create-button">Add New widget</a>
        @endpermission
      </div>
      <div class="col-sm-6">
        <div class="text-right">
          <a href="{{ route('widgets.history') }}" class="btn btn-primary">widget History</a>
        </div>
      </div>
    </div>
    {!! $dataTable->table(['class' => 'table table-bordered','id' =>'widget-table']) !!}
    @permission(('widget_create'))
        <a href="{{ route('widgets.create') }}" class="btn btn-primary">Add New widget</a>
    @endpermission
    @include('partials.panel-close')
    <div id="myModal" class="modal fade" role="dialog">
      <div class="modal-dialog">
        
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Documentation</h4>
          </div>
          <div class="modal-body">

          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>
    @endsection
    @push('scripts')
    <script src="/vendor/datatables/buttons.server-side.js"></script>
    {!! $dataTable->scripts() !!}
    <script type="text/javascript">
    $('#widget-table').on('click', '.btn-delete[data-remote]', function (e) {
        e.preventDefault();
        if (confirm("Are you sure you want to delete"))
         {
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            var url = $(this).data('remote');
             $.ajax({
                 url: url,
                 type: 'DELETE',
                 dataType: 'json',
                 data: {method: '_DELETE', submit: true}
             })
                 .always(function (data) {
                     var count = data.count;
                     if (count == 0) {
                         $('#widget-table').DataTable().draw(false);
                     } else {
                         alert("widget can't be deleted as there are associated widget Account/s (#" + count + ") under the same. Kindly remove the widget Account/s first.");
                     }
                 });
        }
    });
    $(document).on("click",".opendocument",function(){
        $(".modal-body").html($(this).data('value'));
        $('#myModal').modal('show');
    });
    </script>
    @endpush

Now I've updated composer and am trying to use:

    "yajra/laravel-datatables-oracle": "^9.0",
    "yajra/laravel-datatables-buttons": "^4.0",

And when I view the widget index, I get the ajax error dialog

    DataTables warning: table id=widget-table - 
    Ajax error. For more information about this error, 
    please see http://datatables.net/tn/7

When I look in the Laravel.log:

    [2020-07-24 10:30:55] local.ERROR: Call to a member function queryBuilder() on null 
    {"userId":19,"exception":"[object] 
    (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Call to a member function queryBuilder() on null at /Projects/my-app/app/DataTables/WidgetDataTable.php:20)
    [stacktrace]
    #0 [internal function]: App\\DataTables\\WidgetDataTable->ajax()

So, it seems that on this line:

        return $this->datatables
            ->queryBuilder(...

the `datatables` property is not set. So, I am stuck as to how to proceed, and have broken my entire application. Looking for advice on what to try or a guide on how to upgrade the Yajra service implementation without having to modify hundreds of files.

Note, this is cross posted from [here](https://stackoverflow.com/questions/63079701/yajra-datatables-service-implementation-upgrade-from-laravel-5-to-laravel-6). If you can clue me into answer, I will update the SO post.

**Comment by lk77** [comment]
Hello,

there is no $datatables property in the service implementation, which version you  were using ?

**Comment by yajra** [comment]
On recent/current version, is was replaced with the `dataTable($query)` method. Thanks!
