### ISSUE TITLE
Question regarding commit 45c7faf

### ISSUE THREAD

**Issue by underdpt** [yajra/laravel-datatables-buttons#126]
Hello,

I'm facing some issues that i've tracked down to this commit 45c7faf957e10cbfdfa0424d2f0b0765fbb1fd5a. 

This commit introduces a distinction on the data that is passed to the export handler if the export handler is not exactly `Yajra\DataTables\Services\DataTablesExportHandler`, so data passed to a custom export handler is different from that passed to the original handler, so custom handlers are passed columns marked as not-exportable or even full related models when using eager loading on the query.

What's the motive for this change?

I think we should change the check to check if the export handler extends the default export handler with `is_subclass_of` so we use the same data for the default export handler and custom export handlers that extends it.

**Comment by yajra** [comment]
> What's the motive for this change?

When creating a custom export, I realized that only exportable columns are available on the collection thus customization will be limited to those data. Other columns that I need is not available thus I decided to dump all the ajax response when using a custom export class. I can then perform all other mutations I need inside the export class.

Sorry if it break your app? Can you please submit a PR on your proposed solution?

Thanks!

**Comment by underdpt** [comment]
I'll make a PR later today.

Just to mention, you can use a custom action to cutomize your export. I'll often add a `customExport` action to `$actions` , and then on the `customExport` function I'll just get the data I need using `getDataForExport` or `getAjaxResponseData` as needed. So maybe this change isn't neccesary at all.

**Comment by underdpt** [comment]
Fix released on 4.12.1. 

¡Thanks @yajra!
