### ISSUE TITLE
How to export all to csv in ajax?

### ISSUE THREAD

**Issue by bartw2k9** [yajra/laravel-datatables-buttons#141]
### Summary of problem or feature request

How to export all to csv in ajax call - I want export ALL not only one page. Is it possible?

**Comment by yajra** [comment]
Yes, have an outdated examples but should give some idea:

https://datatables.yajrabox.com/services/basic
https://yajrabox.com/docs/laravel-datatables/master/buttons-starter

**Comment by bartw2k9** [comment]
Thanks for reply! I have implemented DataTables in Laravel with buttons package and no console errors:
```html
<script src="/vendor/datatables/buttons.server-side.js"></script>
```
and all just working fine only export button exporting only client side results so if I show All records in show results then I am able to export via button All. But I am using it "old" way using in my ajax get list with just transformer:
```php
        $dataTables = DataTables::eloquent(SearchQueryModel::query());
        $dataTables->setTransformer(BackendSearchQueryTransformer::class);
        return $dataTables->make(true);
```

so looks like buttons.server-side.js not affect. Should it work anyway? or I have to rebuild to use this way:
class UsersDataTable extends DataTable...

**Comment by yajra** [comment]
You need to rebuild using the DataTable class since the export functionality is built-in there.

**Comment by bartw2k9** [comment]
Oki thanks its working now.
