### ISSUE TITLE
Buttons not working after update to 1.1

### ISSUE THREAD

**Issue by Waguilar33** [yajra/laravel-datatables-buttons#15]
### Summary of problem or feature request
I originally install v 1.0 and exporting was working ok. After reading the documentation saw that v 1.1 was available to decide to update. Now all the buttons don't work anymore. I used the [Extended DataTable](https://yajrabox.com/docs/laravel-datatables/7.0/buttons-extended) documentation to upgrade.

### Code snippet of problem
![image](https://cloud.githubusercontent.com/assets/21320293/24461693/204e47f2-145f-11e7-8c22-5af748b5f77b.png)

### System details

- Operating System
- PHP Version 
- Laravel Version 5.4
- Laravel-Datatables-Buttons Version 1.1

**Comment by Waguilar33** [comment]
Update 1: I decide to rollback to v 1.0 with Laravel-Datatables v 7.2 and buttons are working again.

**Comment by yajra** [comment]
Are you still having this issue? Try updating to the latest version and force publish the config. Thanks!

**Comment by Waguilar33** [comment]
Everything is working now. I had to erase everything and install from 0
