### ISSUE TITLE
$dataTable->with() does not allow collections to be passed.

### ISSUE THREAD

**Issue by challgren** [yajra/laravel-datatables-buttons#154]
### Summary of problem or feature request

When version 9.0.0 was released you added more parameter typehints, https://github.com/yajra/laravel-datatables-buttons/blob/master/src/Services/DataTable.php#L688 was changed to only allow `array|string|null` as a value when it should have stayed as `mixed` in the docblock to conform with the View contract https://github.com/laravel/framework/blob/9.x/src/Illuminate/Contracts/View/View.php#L23

I would be willing to do a PR for this to implement the `Illuminate\Contracts\View\View` to make this more consistent with the Laravel framework.

### Code snippet of problem

Details are above but as a Laravel user I would expect DataTables->with() to follow along with the View contract method and allow passing of objects and other types.

### System details

- Operating System: MacOS 12.6
- PHP Version: 8.1.10
- Laravel Version: Laravel 9.31.0
- Laravel-DataTables Version: Started with 9.0.0 but running 9.0.10

**Comment by yajra** [comment]
Thanks for reporting, looking forward to your PR.
