### ISSUE TITLE
datatables-buttons Styling

### ISSUE THREAD

**Issue by EricKwan2014** [yajra/laravel-datatables-buttons#21]
### Datatables Buttons Styling

Thank you so much for your effort.

Moreover, after I saw your demo application styling from:
`http://dt54.yajrabox.com/buttons/eloquent`

How can I customise my buttons styling like semantic UI, etc

Is there any way to add class or any other methods to do so?

Thank you so much

**Comment by yajra** [comment]
Yes there is. See this [link](https://datatables.net/extensions/buttons/examples/styling/semanticui.html) for quick ref.
Just browse the main datatables.net documentation to find more about buttons styling. Thanks!

**Comment by yajra** [comment]
Another link for buttons [options](https://datatables.net/reference/option/#buttons)

**Comment by EricKwan2014** [comment]
Got it, thanks you so much man:) Have a nice day!
