### ISSUE TITLE
Print button opening datatable as HTML on same page without opening a print popup on new page

### ISSUE THREAD

**Issue by hardiktailored** [yajra/laravel-datatables-buttons#23]
### Summary of problem or feature request

I am using Print button to print datatable records. When I click on Print button it opens datatable records as HTML page on same tab in browser without opening a print pop-up. Where it should open print dialog on new page and it should close that page once printing finishes or on cancel click. So it will stay on page where it was clicked. Same like datatables Print example: https://datatables.net/extensions/buttons/examples/print/simple.html

### Code snippet of problem
```
 buttons: [
                    {
                        extend: 'export',
                        text: '<i class="fa fa-external-link" aria-hidden="true"></i>Export <span class="caret"></span>',
                        className: 'custom-dt-export'
                    },
                    {
                        extend: 'print',
                        className: 'custom-dt-print'
                    }
                ]
```

### System details

- Operating System: Ubuntu 12.04
- PHP Version: 5.6
- Laravel Version: 5.4
- Laravel-Datatables Version: 7.2
- Laravel-Datatables-Buttons Version: 1.1

**Comment by yajra** [comment]
@hardiktailored Yes, it is currently the expected behavior. If you can convert it to popup, please do not hesitate to submit a PR. Thanks!

**Comment by yajra** [comment]
Oh do you mean you want the print dialog to open when loaded? Just update `print.blade.php` and add a `window.print()` script on load.

**Comment by hardiktailored** [comment]
@yajra Yes, I already opening print pop-up adding JavaScript `window.print()` at the bottom of the `print.blade.php`  but the problem is, page is opening in the same tab where button was clicked. The print page suppose to open in new tab and should close after print or on cancel of print dialogue.

**Comment by hardiktailored** [comment]
@yajra As a temporary solution I am using below script to print and redirect back to previous URL with searched text in `print.blade.php` and using the search text in `"oSearch": {"sSearch": "{{ $search_text }}"}` to filter records again on the main page.
```
<script type="text/javascript">
    function getParameterByName(name) {
        var match = RegExp('[?&]' + name + '=([^&]*)').exec(window.location.search);
        return match && decodeURIComponent(match[1].replace(/\+/g, ' '));
    }

    window.print();
    var url = new URL(window.location.href);
    var c = getParameterByName("search%5Bvalue%5D");
    window.location.href = document.referrer + '?search=' + c;
</script>
```

**Comment by h4ck3r01** [comment]
I'm having the same issue... I wanted so bad to print in a blank tab instead of the very same... can you tell us anything Yajra?

**Comment by h4ck3r01** [comment]
Change the `buttons.server-side.js` did the trick, placing `window.open()` instead of `window.url`:

```
DataTable.ext.buttons.print = {
        className: 'buttons-print',

        text: function (dt) {
            return '<i class="fa fa-print"></i> ' + dt.i18n('buttons.print', 'Print');
        },

        action: function (e, dt, button, config) {
            var url = _buildUrl(dt, 'print');
            window.open(url);
        }
    };
```

Also insert script on the print template to `autoPrint`:

```
<script>
    window.print();
    setTimeout(function () {
        window.close();
    }, 500);
</script>
```

Thx anyway @yajra awsome package you got here!
