### ISSUE TITLE
DataTransformer found twice

### ISSUE THREAD

**Issue by Waguilar33** [yajra/laravel-datatables-buttons#25]
Not a problem, yet, but I'm configuring everything (working on another project) and i got the following warning as soon as I ran the command:

`composer require yajra/laravel-datatables-buttons`

`Warning: Ambiguous class resolution, "Yajra\Datatables\Transformers\DataTransformer" was found in both "..vendor/yajra/laravel-datatables-oracle/src/Transformers/DataTransformer.php" and "..vendor/yajra/laravel-datatables-buttons/src\Transformers\DataTransformer.php", the first will be used.`

### System details

- Operating System
- PHP Version: 7.1
- Laravel Version: 5.4
- Laravel-Datatables Version: 7.9.3
- Laravel-Datatables-Buttons: 2.02

**Comment by yajra** [comment]
Thanks, `DataTransformer` was removed on `v8` of the main package so I moved it on the buttons table. I think I should rename the transformer on to something else to fix this warning.

**Comment by yajra** [comment]
Fixed on v2.0.3, kindly update and confirm. Thanks!
