### ISSUE TITLE
PHPExcel_Calculation_Exception when exporting data starting with =

### ISSUE THREAD

**Issue by Arkhas** [yajra/laravel-datatables-buttons#53]
### Summary of problem or feature request

When exporting a datatables with some datas starting with `=` I got the following error : 

`PHPExcel_Calculation_Exception: exported-data!Z2 -&gt; internal error in file /var/www/app/vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell.php on line 293
` 

There might be a solution here : https://stackoverflow.com/questions/31827960/php-fatal-error-uncaught-exception-phpexcel-calculation-exception

### System details

- Operating System : Ubuntu 16.04.2 LTS
- PHP Version: PHP 7.1.8
- Laravel Version:  5.5.19
- Laravel-DataTables Version 
Buttons : 3.1
laravel-datatables-oracle: 8.3.2

**Comment by yajra** [comment]
Sorry for late response. I think this issue should be raise on the [laravel-excel](https://github.com/Maatwebsite/Laravel-Excel) repo. Thanks!
