### ISSUE TITLE
Scope using with() method

### ISSUE THREAD

**Issue by jay-shah-rushiinfotech** [yajra/laravel-datatables-buttons#55]
### Summary of problem or feature request

Scope not allowed to add custom condition based on role or two different session user id.
Add functionality of attributes on scope.
### Code snippet of problem
```
namespace Yajra\Datatables\Contracts;

protected $attributes = []; //  or protected static $attributes = [];
public function with($key, $value = null)
    {
        if (is_array($key)) {
            $this->attributes = array_merge($this->attributes, $key);
        } else {
            $this->attributes[$key] = $value;
        }

        return $this;
    }
public function __get($key)
    {
        if (array_key_exists($key, $this->attributes)) {
            return $this->attributes[$key];
        }

        return null;
    }
```
### System details

- Operating System - Ubuntu
- PHP Version - 7.1
- Laravel Version 5.3
- Laravel-DataTables Version 8.3

**Comment by yajra** [comment]
Not sure if I get this right, but maybe the role condition you're referring should be added before calling the `with` method?

```php
public function index (UsersDT $dt) {
  if (..) { 
    $dt->with(...); 
  }

  return $dt->render('view');
}

**Comment by jay-shah-rushiinfotech** [comment]
It's for the datable scope not for the datatable service.

`namespace Yajra\Datatables\Contracts;`

So we can use `with` the method in the datatable scope.

**Comment by yajra** [comment]
If dataTable scope, use `addScope(new ScopeClass)`.
