### ISSUE TITLE
[Question] How to add support for "copy" button

### ISSUE THREAD

**Issue by Omranic** [yajra/laravel-datatables-buttons#6]
First of all thank you very much for this Super Awesome package! 💯 
Is there anyway to add support for "copy" button? Example maybe?

**Comment by yajra** [comment]
No example yet but I think you can already do this by adding the `js` script for `copy` button and just appending it on the `buttons` array of `DataTable` class.

```php
'buttons' => ['copy', 'csv', 'excel', 'pdf', ...]
```
