### ISSUE TITLE
Laravel 5.6 compatible

### ISSUE THREAD

**Issue by manuelcalerosolis** [yajra/laravel-datatables-buttons#60]
When will it be compatible with version 5.6 of laravel?

When I install the package I get the following error.

c:\xampp\htdocs\panelhotel>composer require yajra/laravel-datatables-buttons:^3.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yajra/laravel-datatables-buttons 3.0 -> satisfiable by yajra/laravel-datatables-buttons[v3.0.0].
    - Conclusion: remove laravel/framework v5.6.11
    - Conclusion: don't install laravel/framework v5.6.11
    - yajra/laravel-datatables-buttons v3.0.0 requires illuminate/console 5.4.*|5.5.* -> satisfiable by laravel/framework[5.4.x-dev, 5.5.x-dev], illuminate/console[5.4.x-dev, 5.5.x-dev, v5.4.0, v5.4.13, v5.4.17, v5.4.19, v5.4.27, v5.4.36, v5.4.9, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39].

- Operating System
- PHP Version 7.1
- Laravel Version 5.6
- Laravel-DataTables Version 8.0

**Comment by sangnguyenplus** [comment]
Use it in composer.json

```
"yajra/laravel-datatables-buttons": "~3.2"
```

It's working for me.

**Comment by cferrante** [comment]
@sangnguyenplus, your recommendation works for me as well.

I am having issues adding custom buttons. Have you had any success with Laravel 5.6 adding a custom button?
