### ISSUE TITLE
Upgrading Maatwebsite/Laravel-Excel to version 3.0

### ISSUE THREAD

**Issue by sangnguyenplus** [yajra/laravel-datatables-buttons#61]
Can you update Maatwebsite/Laravel-Excel to version 3.0?
Laravel Excel is released version 3.0 with many new features.
I see this package still use old Laravel Excel version. And it always shows a warning when running `composer update` command.

```
Package phpoffice/phpexcel is abandoned, you should avoid using it. Use phpoffice/phpspreadsheet instead.
```

Thanks for a greate package!

**Comment by lk77** [comment]
+1 we need to upgrade too

**Comment by meyer59** [comment]
+1 please upgrade

**Comment by chimpanze** [comment]
+1

**Comment by backstageel** [comment]
+1

**Comment by yajra** [comment]
I just made a WIP implementation for Excel 3.0 compatibility and is now available for testing on the master branch. Can you please guys check and advise for suggestions/feedbacks?

Also, do you think this is a candidate for a Major bump or just a minor bump to v3.3.0?

**Comment by yajra** [comment]
Oh, I just realized that I should done it thru PR. But YOLO, I guess it's fine on master branch. :)

**Comment by drbyte** [comment]
It works, but the old Excel and CSV exports included column headings, and this one doesn't.
(didn't test PDF)

**Comment by yajra** [comment]
@drbyte good catch, I just updated the code and implemented WithHeadings. Thanks!

**Comment by drbyte** [comment]
That's fixed now. 

Do you think it will matter that you've changed the default from `.xls` to `.xlsx` ?
(Doesn't matter to me, but it's a "change".)

**Comment by drbyte** [comment]
@yajra wrote:
> Also, do you think this is a candidate for a Major bump or just a minor bump to v3.3.0?

I'm on the fence. While the changes to how this package works are minimal (xls/xlsx), given that some people might have the older Maat/Excel 2.x package in use for other purposes in their apps, I suggest treating this as a Major bump. It will minimize confusion.

**Comment by drbyte** [comment]
... hmmm, but if you bump this to 4.0 then the Editor package will need its dependency in composer.json updated as well.

**Comment by lk77** [comment]
i've upgraded to 4.0.x-dev and my exports still works, so it's sounds good. For the major bump we don't have the choice i think, since it will not work anymore with 2.1, it's a breaking change.

**Comment by meyer59** [comment]
Hi
Any news when this update will be avalaible on the master branch? 
We need to upgrade to the new excel 3.0
Thanks

**Comment by sangnguyenplus** [comment]
Hi @meyer59,

I see that it's working well now but it's not released yet. You can use branch "4.0.x-dev" to work with it now.

```
"yajra/laravel-datatables-buttons": "4.0.x-dev"
```

**Comment by wowzaaa** [comment]
+1

**Comment by nasirkhan** [comment]
the new version has not been released yet, why is it closed then?

**Comment by westonwatson** [comment]
It's not a huge deal. But I'd like to get rid of this composer warning... Any word?

**Comment by OzanKurt** [comment]
@yajra 

I see that you're currently using the "Collection Export". Are you planning to add the "Query Export" as well, since it prevents PHP from running out of memory while exporting large tables.
