### ISSUE TITLE
Using the buttons from html builder

### ISSUE THREAD

**Issue by pralhadstha** [yajra/laravel-datatables-buttons#62]
### Summary of problem or feature request
I have tried to use the html builder to create the datatable and other features. I have a wrapper outside the html builder and now i want to use the export and other features. I can see the buttons package using the html builder but is the reverse possible? Adding the buttons as the html builder's extension?

As i have the custom queries and columns getting method that has been implemented in html builder.  If we use the `Yajra\DataTables\Services\DataTable` and implement the html() and query() that seems to be duplicating the queries i am implementing. Also i need to switch the classes for the tables that uses the export buttons and that doesn't use.

### Code snippet of problem

Using the buttons with html() and getColumns()

```
class UsersDataTable extends DataTable
{
    //...some default stubs deleted for simplicity.

    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->parameters([
                        'dom'          => 'Bfrtip',
                        'buttons'      => ['export', 'print', 'reset', 'reload'],
                    ]);
    }

    protected function getColumns()
    {
        return [
            'id',
            'name',
            'email',
            'created_at',
            'updated_at',
        ];
    }
}
```

Is it possible to use like this:

```
Route::get('users', function(Builder $builder) {
    if (request()->ajax()) {
        return DataTables::of(User::query())->toJson();
    }

    $html = $builder->columns([
                ['data' => 'id', 'name' => 'id', 'title' => 'Id'],
                ['data' => 'name', 'name' => 'name', 'title' => 'Name'],
                ['data' => 'email', 'name' => 'email', 'title' => 'Email'],
                ['data' => 'created_at', 'name' => 'created_at', 'title' => 'Created At'],
                ['data' => 'updated_at', 'name' => 'updated_at', 'title' => 'Updated At']),
            ]) ->parameters([
                        'dom'          => 'Bfrtip',
                        'buttons'      => ['export', 'print', 'reset', 'reload'],
                    ]);

    return view('users.index', compact('html'));
});

```
### System details
- Operating System: Windows | Linux
- PHP Version: 7.2
- Laravel Version: 5.5
- Laravel-DataTables Version: 8.0

**Comment by lk77** [comment]
what is the problem ? it's not working ? i've used buttons in service implementation and it's working well.

**Comment by Kamleshpaul** [comment]
/home/appcloud/Downloads/IMG_0199.jpg

**Comment by layersoft** [comment]
:cry:

**Comment by yajra** [comment]
Buttons are working well as @lk77 have mentioned. Please open a new issue if needed.
