### ISSUE TITLE
Laravel 5.6 Custom Button - Question

### ISSUE THREAD

**Issue by cferrante** [yajra/laravel-datatables-buttons#66]
This package is awesome! 
I was zooming along, but then tried to add a custom button...oops

Following instruction here:
[](https://yajrabox.com/docs/laravel-datatables/master/buttons-custom)
Breaks the previously working page (with buttons) and produces javascript console error 
"Uncaught Unknown button type: myCustomAction"

Has anyone been able to implement a custom button using Laravel 5.6? Do you have any idea where I might be going wrong?

This is what the article describes:
```php
namespace App\DataTables;

use App\User;
use Yajra\DataTables\Services\DataTable;

class UsersDataTable extends DataTable
{
    protected $actions = ['print', 'excel', 'myCustomAction'];

    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->parameters([
                        'dom'          => 'Bfrtip',
                        'buttons'      => ['print', 'excel', 'myCustomAction'],
                    ]);
    }

    public function myCustomAction()
    {
        //...your code here.
    }

}
```

- Windows 10 / using vagrant  Ubuntu 18.04
- PHP Version 7.2.7-1
- Laravel Version 5.6
- Laravel-DataTables Version - tried several versions
                                                 ^8.0
                                                 ^8.4
- Laravel-DataTables-Buttons - ^3.0
                                                - ~3.2
Tried the full package install - "yajra/laravel-datatables": "^1.0"

**Comment by cferrante** [comment]
@yajra - so impressed and surprised with how quickly you responded!

This is what actually works for me (so far):

```
    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->parameters([
                        'dom'          => 'Bfrtip',
                        'buttons'      => ['print', 'excel', 
                           ['text' => 'myCustomAction',
                           'className' => '',
                           'action' => 'function(e, dt, node, config) { alert("My Custom Callback") }'
                           ]
                        ],
                    ]);
    }
```
Does it seem like I am going the right direction?

I have been programming C/C++, Java, etc. for many years, but am very new to Laravel, so again, am especially appreciative of your work!!

**Comment by yajra** [comment]
Thanks and Yes, this looks like at the right path. When you want some action on the server side, you need to append the `action` query to your request. Something like:

```
'action' => 'function(e, dt, node, config) {
  $.ajax({
    url: 'datatables',
    data: {action: 'myCustomAction'},
    success: function(response) { console.log(response) }
  })
}'
```

Setting the action value will tell the dataTable class which method to trigger to process the response.
