### ISSUE TITLE
Individual Column Filtering

### ISSUE THREAD

**Issue by markdave27** [yajra/laravel-datatables-buttons#79]
### Summary of problem or feature request
Does DataTables Button supports the setup with individual column filtering?

Here is the example of the setup, https://datatables.net/extensions/fixedcolumns/examples/styling/col_filter.html

### Code snippet of problem
Integration is like the guide here https://yajrabox.com/docs/laravel-datatables/master/buttons-starter

### System details
- Windows 10
- PHP 7.1.1
- Laravel 5.4.*
- Laravel DataButtons 3.0, Laravel DataTables Oracle 8.*

**Comment by yajra** [comment]
Yes column search is supported. See https://datatables.yajrabox.com/eloquent/multi-filter-select for ref and sorry for late reply.
