### ISSUE TITLE
Not working with laravel 5.7

### ISSUE THREAD

**Issue by zajinx** [yajra/laravel-datatables-buttons#80]
### Summary of problem or feature request

Unable to install on laravel 5.7

### Code snippet of problem

composer require yajra/laravel-datatables-buttons:^4.0
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for yajra/laravel-datatables-buttons 4.0 -> satisfiable by yajra/laravel-datatables-buttons[v4.0.0].
    - Conclusion: remove laravel/framework v5.7.12
    - Conclusion: don't install laravel/framework v5.7.12
    - yajra/laravel-datatables-buttons v4.0.0 requires illuminate/console 5.5.*|5.6.* -> satisfiable by illuminate/console[5.5.x-dev, 5.6.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.26, v5.6.27, v5.6.28, v5.6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6.39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/console 5.6.x-dev|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.0|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.1|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.10|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.11|don't install laravel/framework v5.7.12
    - don't install illuminate/console v5.6.12|don't install laravel/framework v5.7.12

### System details

- Operating System Windows 10 x64
- PHP Version 7.2
- Laravel Version 5.7.12
- Laravel-DataTables Version 8.0

**Comment by zajinx** [comment]
nvm works if you specify 4.*

composer require yajra/laravel-datatables-buttons:4.*
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 6 installs, 0 updates, 0 removals
  - Installing markbaker/complex (1.4.7): Loading from cache
  - Installing phpoffice/phpspreadsheet (1.5.0): Loading from cache
  - Installing maatwebsite/excel (3.1.3): Downloading (100%)
  - Installing laravelcollective/html (v5.7.1): Loading from cache
  - Installing yajra/laravel-datatables-html (v3.8.1): Downloading (100%)
  - Installing yajra/laravel-datatables-buttons (v4.4.0): Loading from cache
phpoffice/phpspreadsheet suggests installing mpdf/mpdf (Option for rendering PDF with PDF Writer)
phpoffice/phpspreadsheet suggests installing dompdf/dompdf (Option for rendering PDF with PDF Writer)
phpoffice/phpspreadsheet suggests installing tecnickcom/tcpdf (Option for rendering PDF with PDF Writer)
phpoffice/phpspreadsheet suggests installing jpgraph/jpgraph (Option for rendering charts, or including charts with PDF or HTML Writers)
yajra/laravel-datatables-buttons suggests installing dompdf/dompdf (Allows exporting of dataTable to PDF using the DomPDF.)
yajra/laravel-datatables-buttons suggests installing barryvdh/laravel-snappy (Allows exporting of dataTable to PDF using the print view.)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi
Discovered Package: beyondcode/laravel-dump-server
Discovered Package: fideloper/proxy
Discovered Package: laravel/passport
Discovered Package: laravel/tinker
Discovered Package: laravelcollective/html
Discovered Package: maatwebsite/excel
Discovered Package: nesbot/carbon
Discovered Package: nunomaduro/collision
Discovered Package: yajra/laravel-datatables-buttons
Discovered Package: yajra/laravel-datatables-html
Discovered Package: yajra/laravel-datatables-oracle
Package manifest generated successfully.

**Comment by Luismij** [comment]
Thanks!! This works for me too 👍
