### ISSUE TITLE
Dump autoload throws error of markbaker/complex dependency

### ISSUE THREAD

**Issue by sagarpatel9697** [yajra/laravel-datatables-buttons#88]
- PHP Version: 7.1.16
- Laravel Version: 5.7.26
- Laravel-DataTables Version: 8.0

### Summary of problem

when i install **laravel-datatables-buttons** package with `composer require yajra/laravel-datatables-buttons` command it is going good but when it comes on post autoload dump it throws error like below 

`Warning: Uncaught ErrorException: require(E:\wamp64\www\laravel-repo\vendor\composer/../markbaker/complex/classes/src/functions/abs.php): failed to open stream: No such file or directory`

When i looked in `vendor\markbaker\complex` path in local repository, complex directory hasn't any sub directory or any files.

![datatable_error](https://user-images.githubusercontent.com/25764632/52895103-85914600-31db-11e9-8479-c97fb5371beb.png)

**Comment by yajra** [comment]
I think the issue is on that package. Please file an issue on their repo instead. Thanks!
