### ISSUE TITLE
Multiple instances of a button via datatables-buttons config file

### ISSUE THREAD

**Issue by karmendra** [yajra/laravel-datatables-buttons#91]
I am using latest yajra datatables on Laravel 5.7.

I am trying to achieve creation of multiple instances button class to group buttons. so that I can append them to different dom elements outside datatables.

See the example code [here](https://datatables.net/extensions/buttons/examples/initialisation/multiple.html)

Well, I am able to achieve this by adding the sample code in js directly. but I want to add this in getBuilderParameters() i.e. datatables-buttons.php configuration file.

**Comment by yajra** [comment]
You mean the script that adds the buttons? Another way to extend a default script is by creating new script template (html plugin). This is what I sometimes do.

When you publish the package view, there is a `datatables::script` blade template that is being used to generate the scripts. Just create a clone file and append your common scripts there. Afterwards, on your builder, just chain `->setTemplate('datatables::new-script')`.
