### ISSUE TITLE
Error when install with laravel-datatables-oracle v9.4.0

### ISSUE THREAD

**Issue by sanvu88** [yajra/laravel-datatables-buttons#95]
### Summary of problem
When try install, I received an error message: " Your requirements could not be resolved to an installable set of packages."

###  Error message:
Problem 1
    - Can only install one of: yajra/laravel-datatables-oracle[8.0.x-dev, v9.4.0].
    - Can only install one of: yajra/laravel-datatables-oracle[v9.4.0, 8.0.x-dev].
    - Can only install one of: yajra/laravel-datatables-oracle[8.0.x-dev, v9.4.0].
    - yajra/laravel-datatables-buttons v3.0.0 requires yajra/laravel-datatables-oracle 8.* -> satisfiable by yajra/laravel-datatables-oracle[8.0.x-dev].
    - Installation request for yajra/laravel-datatables-buttons 3.0 -> satisfiable by yajra/laravel-datatables-buttons[v3.0.0].
    - Installation request for yajra/laravel-datatables-oracle ~9.4 -> satisfiable by yajra/laravel-datatables-oracle[v9.4.0].

### System details

- Operating System: Nginx
- PHP Version: 7.2
- Laravel Version: 5.8
- Laravel-DataTables Version: 9.4.0

**Comment by f7eco** [comment]
yes it is a problem!!! same problem:
Operating System: Windows 10
PHP Version: 7.2
Laravel Version: 5.8
Laravel-DataTables Version: 9.4.1

**Comment by yajra** [comment]
You might be using `yajra/laravel-datatables-buttons v3.0.0` somewhere? Use v4.0 instead. Or use the  all in one installer `composer require yajra/laravel-datatables:^1.5`.

**Comment by yajra** [comment]
See #94 for a solution too. Thanks!
