### ISSUE TITLE
Creating button from controller

### ISSUE THREAD

**Issue by SSEsmaeeli** [yajra/laravel-datatables-buttons#97]
Is it Possible to create Buttons from controller? (not datatable that is created by Service).

e.g. I have this : 

return Datatables::of($users)
            ->editColumn('city_id', function($user) {
            	return $user->city_name;
            })
            ->editColumn('country_id', function($user) {
            	return $user->country_name;
            })
        ->make(true);

How can I send button parameters ? is it possible ?

**Comment by yajra** [comment]
What do you mean by button parameters? Can you please elaborate.

Anyways, it's possible but you will need to do some extra coding for it to work.

**Comment by SSEsmaeeli** [comment]
I mean, Enabling buttons in non-service mode, I searched a lot to see an example of how to enable buttons(export and ...) in non-service mode, but unfortunately did not see anything ... would u pls tell me how to use it ? or gimme a link that represent it ?
another question is how can I change style of buttons? (I wanna use bootstrap buttons like btn-success or something ...), Is there a direct way to do that ? or I should handle it with jquery myself?

**Comment by yajra** [comment]
Not possible as the buttons were part of the service class. Thanks!
